# Pre-commit configuration for automatic code formatting and checking
#
# Can be installed with:
# $ pip install pre-commit
# $ pre-commit install
#

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace  # remove trailing whitespaces except markdown files
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer  # add empty line at the end of files
    -   id: check-yaml  # Check yaml
        args: ['--unsafe']
    -   id: check-added-large-files  # Check if no file larger than 2MB has been added.
        args: ['--maxkb=8048']
-   repo: https://github.com/psf/black  # Automatic code format
    rev: 23.10.0
    hooks:
    -   id: black
-   repo: https://github.com/hadialqattan/pycln  # Clean unused imports
    rev: v2.3.0
    hooks:
    -   id: pycln
        args: ["-a", "-x", "-v"]
-   repo: https://github.com/pycqa/isort  # Sort project imports
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile=black"]
        exclude: 'example_repo/.*'  # ignore, as sorting in aiviro repo and customer's repo is different - https://stackoverflow.com/questions/73471822/isort-sorting-things-differently-when-running-locally-than-in-ci-other-machines
-   repo: https://github.com/PyCQA/flake8  # Check code consistency
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["--ignore=F541,N813,W503,W605,E203", "--max-line-length=120"]
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        additional_dependencies:
        - "pylint_pydantic"
        args: [ "--load-plugins=pylint_pydantic",
                "--extension-pkg-whitelist=pydantic",
                "-E",
                "--disable=E0401",
                "--disable=E1101",
                "--disable=E1131"
        ]
